export const MILESTONES = [
  {
    id: 1,
    minutes: 20,
    icon: '💓',
    title: 'Tension artérielle',
    desc: 'Ta tension artérielle et ton rythme cardiaque reviennent à la normale',
    color: '#f43f5e',
  },
  {
    id: 2,
    minutes: 480,
    icon: '💨',
    title: 'Oxygène retrouvé',
    desc: 'Le taux de monoxyde de carbone dans ton sang diminue de moitié',
    color: '#3b82f6',
  },
  {
    id: 3,
    minutes: 1440,
    icon: '❤️',
    title: 'Cœur protégé',
    desc: 'Le risque d\'infarctus du myocarde commence à diminuer',
    color: '#f43f5e',
  },
  {
    id: 4,
    minutes: 2880,
    icon: '👃',
    title: 'Odorat & Goût',
    desc: 'Ton odorat et ton goût s\'améliorent sensiblement',
    color: '#a78bfa',
  },
  {
    id: 5,
    minutes: 4320,
    icon: '🫁',
    title: 'Poumons libres',
    desc: 'Les bronches se dilatent, respirer devient plus facile',
    color: '#10b981',
  },
  {
    id: 6,
    minutes: 20160,
    icon: '🩸',
    title: 'Circulation',
    desc: 'La circulation sanguine s\'améliore dans les mains et les pieds',
    color: '#f97316',
  },
  {
    id: 7,
    minutes: 43200,
    icon: '💪',
    title: 'Poumons +30%',
    desc: 'La fonction pulmonaire s\'améliore de 30%',
    color: '#10b981',
  },
  {
    id: 8,
    minutes: 129600,
    icon: '😮‍💨',
    title: 'Moins d\'essoufflement',
    desc: 'La toux diminue et l\'essoufflement s\'améliore nettement',
    color: '#06b6d4',
  },
  {
    id: 9,
    minutes: 259200,
    icon: '🛡️',
    title: 'Immunité renforcée',
    desc: 'Moins d\'infections des voies respiratoires',
    color: '#8b5cf6',
  },
  {
    id: 10,
    minutes: 525600,
    icon: '⭐',
    title: '1 an sans tabac !',
    desc: 'Le risque coronarien est réduit de moitié par rapport à un fumeur',
    color: '#f59e0b',
  },
  {
    id: 11,
    minutes: 2628000,
    icon: '🧠',
    title: 'AVC : risque divisé',
    desc: 'Le risque d\'AVC devient similaire à celui d\'un non-fumeur',
    color: '#a78bfa',
  },
  {
    id: 12,
    minutes: 5256000,
    icon: '🏅',
    title: 'Cancer ÷2',
    desc: 'Le risque de cancer du poumon est réduit de moitié',
    color: '#10b981',
  },
  {
    id: 13,
    minutes: 7884000,
    icon: '🏆',
    title: '15 ans — Victoire totale',
    desc: 'Le risque coronarien est identique à celui d\'un non-fumeur',
    color: '#f59e0b',
  },
];

export const TIPS = [
  'Bois un grand verre d\'eau froide à petites gorgées.',
  'Fais 10 respirations profondes et lentes.',
  'Marche 5 minutes à l\'extérieur.',
  'Mâche un chewing-gum sans sucre.',
  'Appelle ou envoie un message à quelqu\'un que tu aimes.',
  'Fais 20 pompes ou sauts en étoile.',
  'Brosse-toi les dents — le goût propre coupe l\'envie.',
  'Mange quelques noix ou fruits secs.',
  'Prends une douche froide (ça marche vraiment !).',
  'Compte à rebours de 100 à 0 en multipliant par 3.',
  'Rappelle-toi pourquoi tu as décidé d\'arrêter.',
  'L\'envie dure en moyenne 3 à 5 minutes — tiens bon !',
  'Ferme les yeux et visualise tes poumons roses et sains.',
  'Écoute ta chanson préférée en entier.',
  'Dessine ou griffonne quelque chose sur une feuille.',
];

export const ACHIEVEMENTS = [
  { id: 'first_hour', minutes: 60, icon: '🌱', title: 'Première heure', desc: 'Tu as tenu ta première heure !' },
  { id: 'first_day', minutes: 1440, icon: '🌟', title: 'Premier jour', desc: '24 heures sans tabac, bravo !' },
  { id: 'three_days', minutes: 4320, icon: '💎', title: '3 jours', desc: 'Les pires symptômes sont derrière toi !' },
  { id: 'one_week', minutes: 10080, icon: '🔥', title: 'Une semaine', desc: 'Une semaine entière sans cigarette !' },
  { id: 'two_weeks', minutes: 20160, icon: '⚡', title: 'Deux semaines', desc: 'Ta circulation sanguine s\'améliore !' },
  { id: 'one_month', minutes: 43200, icon: '🏅', title: 'Un mois', desc: 'Incroyable ! Un mois complet !' },
  { id: 'three_months', minutes: 129600, icon: '🌙', title: 'Trois mois', desc: 'Ton essoufflement diminue vraiment !' },
  { id: 'six_months', minutes: 259200, icon: '🌈', title: 'Six mois', desc: 'La moitié d\'une année sans tabac !' },
  { id: 'one_year', minutes: 525600, icon: '🏆', title: 'Un an !', desc: 'Ton risque cardiaque est divisé par 2 !' },
];
